# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_house', models.CharField(max_length=10)),
                ('years', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('num_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('launch_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fund', to='portfolio.Customer')),
            ],
        ),
    ]
