# Generated by Django 2.0.2 on 2018-02-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Fund', to='portfolio.Customer'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='portfolio.Customer'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='portfolio.Customer'),
        ),
    ]
